Repository livingbio/pr-lint, pull requests merged in 2024-06, with the labels that each got.

#1 init project
  .github/dependabot.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/pr-lint.yml
  .github/workflows/python-publish.yml
  .pre-commit-config.yaml
  README.md
  poetry.lock
  pyproject.toml
  src/pr_lint/__init__.py
  src/pr_lint/main.py
  src/pr_lint/py.typed
  src/pr_lint/tests/__init__.py
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[U0001f34eupdate(v2.0) version updateU0001f34e].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[U0001f41bfix correct typoU0001f41b].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[U0001f41bu4feeu590d correct typoU0001f41b].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[U0001f680feature(add-new) add a new featureU0001f680].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[bug fix issue U0001f41e].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[feature(add-new) add a new feature].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[fix correct typo].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[no type].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[not an emoji prefix but contains U0001f680 emoji].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[u4feeu590duff1au66f4u6b63u767bu5f55u65b9u6cd5u4e2du7684u9519u5b57].json
  src/pr_lint/tests/test_main.py
Labels: Type: Feature

#5 ✨fix the rule
  .github/workflows/pr-lint.yml
  src/pr_lint/formatter.py
  src/pr_lint/linter.py
  src/pr_lint/main.py
  src/pr_lint/tests/__init__.py
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[U0001f34eupdate(v2.0) version updateU0001f34e].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[U0001f41bfix correct typoU0001f41b].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[U0001f41bu4feeu590d correct typoU0001f41b].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[U0001f680feature(add-new) add a new featureU0001f680].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[bug fix issue U0001f41e].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[feature(add-new) add a new feature].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[fix correct typo].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[no type].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[not an emoji prefix but contains U0001f680 emoji].json
  src/pr_lint/tests/__snapshots__/test_main/test_clean_title[u4feeu590duff1au66f4u6b63u767bu5f55u65b9u6cd5u4e2du7684u9519u5b57].json
  src/pr_lint/tests/test_main.py
Labels: ✨Type: Feature, Impact: RD

#9 fix #8 remove starting and ending spaces @lucemia
  src/pr_lint/linter.py
Labels: Type: CI, Impact: RD

#11 fix #10 compose action @lucemia
  .github/workflows/pr-lint.yml
  action.yml
Labels: Type: CI, Impact: RD

#15 Fix: allow dash in usernames in PR title linting @geminixiang
  src/pr_lint/linter.py
Labels: Type: Bug, Impact: RD

#17 ✨ Fix #16 icon emoji ordering @lucemia
  src/pr_lint/formatter.py
Labels: ✨Type: Feature, Impact: RD

#21 fix #20 assume assignee is owner @geminixiang
  .github/workflows/pr-lint.yml
  src/pr_lint/formatter.py
  src/pr_lint/linter.py
  src/pr_lint/tests/__init__.py
  src/pr_lint/tests/test_utils.py
  src/pr_lint/utils.py
Labels: Type: CI, Impact: RD
